### ISSUE TITLE
Head of staff hardsuits do not fit Unathi

### ISSUE THREAD

**Issue by Shadowtail117** [vlggms/tegustation-bay12#22]
#### Description of issue

The head of staff hardsuits available in the auxiliary EVA storage do not fit unathi because of their digitigrade legs, and are thus unwearable. It is possible this also extends to skrell.

#### Difference between expected and actual behavior

Given that unathi can be heads of staff now, it makes sense that they can wear the hardsuits intended for them.

#### Steps to reproduce

Self-explanatory.

#### Specific information for locating

Likely the issue that the boots are not designed for digitigrade feet. The medical EVA hardsuit works for plantigrade and digitigrade, and the appropriate behavior can likely be taken from there.

#### Length of time in which bug has been known to occur

Probably forever, but only became an issue after #12.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: ccB-de4c
Current map: SEV Torch

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by anconfuzedrock** [comment]
Thing is you also need sprites for the alt suits. at minimum azlan's facelift suit pr on bay (which we got permission to port with credits given) gives command voidsuit sprites, maybe more, so we'll touch that up when we put that in.

**Comment by Cupax3** [comment]
> Thing is you also need sprites for the alt suits. at minimum azlan's facelift suit pr on bay (which we got permission to port with credits given) gives command voidsuit sprites, maybe more, so we'll touch that up when we put that in.

Fixed, then?

**Comment by anconfuzedrock** [comment]
Nope, command voidsuits are in now, but all the head of staff hardsuits (except the CE hardsuit, which always fit everyone) are still restricted. You *could* quickly edit the suits so all can wear them, but it'd be significantly ugly.
