### ISSUE TITLE
You don't fall when walking on a catwalk in high heels.

### ISSUE THREAD

**Issue by EgorDinamit** [vlggms/tegustation-bay12#36]
#### Description of issue

You don't fall when walking on a catwalk in high heels.

#### Difference between expected and actual behavior

You don't fall when walking on a catwalk in high heels.

#### Steps to reproduce

1. Wear high heels.
2. Step on the catwalk.
3. Anger.

#### Specific information for locating

Catwalk.

#### Length of time in which bug has been known to occur

For eternity

#### Client version, Server revision & Game ID

Everything.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

**Comment by Cupax3** [comment]
@EgorDinamit How serious were you when you made this issue?

**Comment by EgorDinamit** [comment]
> @EgorDinamit How serious were you when you made this issue?

Not serious at all. As funny as it'd be, we don't really want to punish people for their choice of shoes.

**Comment by Cupax3** [comment]
Closing.
